### ISSUE TITLE
你好，想询问一下，图片不存在。

### ISSUE THREAD

**Issue by OuOumm** [YueZhiNai/GitStatic#1]
看了下应该是要去发布一个标签，这个时候，js才会去缓存github的东西，所以有考虑更新一下下嘛~每上传一张照片，发布一个版本，获取到对应版本的js链接，就可以实现图片的获取了欸。

**Comment by YueZhiNai** [comment]
导航至[GithubStatic](https://github.com/MliKiowa/GithubStatic)
